next part of homework
dmitry-tkachuk/thinknetica-ruby pull request #3
Opened 2022-12-27 15:26 UTC by dmitry-tkachuk

"evolution" of previous task

2022-12-30 12:04 UTC, shilin-anton requested changes
оставил несколько комментариев.
поправь, пожалуйста, и будет прекрасно!

2022-12-30 12:04 UTC, shilin-anton commented on part_3/route.rb
> +  def middle(station)
плохое название метода, не понятно что он делает. переименуй на "add_middle_station"

2022-12-30 12:04 UTC, shilin-anton commented on part_3/main.rb
> +  def create_new_route
все-таки не корректно работает метод создания маршрутов (идеологически)
что если я создам несколько станций и потом из них захочу "собрать" маршрут?
плюс, я хочу создать маршрут из 3х станций? - **_!!!этот кейс сделаем в след задании!!!_**

давай перепишем, что бы станции не создавались внутри метода create_new_route, а что бы пользователь должен был сначала создать станции из своего раздела меню (1 пункт). Потом при создании маршрута ему должен выдаваться список станций и запрос "выберите первую станцию". Далее "выберите последнюю станцию".
При этом было бы идеально, если при втором выборе (выберите последнюю станцию), "первая" уже отсутствовала в списке, т.к. она уже выбрана.

2022-12-30 12:14 UTC, dmitry-tkachuk commented on part_3/main.rb
> +    if type <= 1 && type.positive?
done

2022-12-30 12:24 UTC, dmitry-tkachuk commented on part_3/main.rb
> +    if course == 1
Исправил условие, теперь если не 1 или 2 возвращает в меню.

2022-12-30 12:31 UTC, dmitry-tkachuk commented on part_3/main.rb
> +    puts "Пассажирский поезд №#{number + 1} успешно создан"
Исправил обработку ввода от пользователя и вывод сообщения

2022-12-30 12:31 UTC, dmitry-tkachuk commented on part_3/main.rb
> +    puts "Грузовой поезд №#{number + 1} успешно создан"
Аналогично предыдущему

2022-12-30 13:06 UTC, dmitry-tkachuk commented on part_3/route.rb
> +  def middle(station)
done

2022-12-30 13:08 UTC, dmitry-tkachuk commented on part_3/main.rb
> +    number = gets.chomp.to_i - 1
Такой проверки не было, добавил.

2022-12-30 17:23 UTC, dmitry-tkachuk commented on part_3/main.rb
> +  def create_new_route
done

2022-12-31 11:07 UTC, shilin-anton commented
все гуд, но оставил один комментарий.

2022-12-31 12:44 UTC, dmitry-tkachuk commented on part_3/route.rb
> +  def remove_middle(station)
done

2022-12-31 12:45 UTC, shilin-anton requested changes

2023-01-02 13:54 UTC, dmitry-tkachuk commented on part_3/main.rb
> +  def trains_list
создал отдельный метод

2023-01-02 16:47 UTC, shilin-anton requested changes

2023-01-02 16:47 UTC, shilin-anton commented on part_3/main.rb
> +    puts "Выберите станцию"
наверное лучше сначала вывести путс а потом уже список станций

2023-01-02 16:47 UTC, shilin-anton commented on part_3/main.rb
> +      return
следует перезапустить метод, а не выбросить юзера в главное меню

2023-01-02 16:47 UTC, shilin-anton commented on part_3/main.rb
> +    elsif @stations[number].trains == []
никогда не проверяй так массив на "пустоту". Используй встроенный метод:
[].empty?

2023-01-02 16:47 UTC, shilin-anton commented on part_3/main.rb
> +      #break if gets.chomp == "exit"
удали уже этот несчастный комментарий)

2023-01-02 16:47 UTC, shilin-anton commented on part_3/main.rb
> +    if last >= (@stations.count) || last < 0 #last = gets.chomp.to_i - 1
к чему этот комментарий?

2023-01-02 16:47 UTC, shilin-anton commented on part_3/main.rb
> +      route = Route.new(stations_list[first], stations_list[last])
метод не работает..
во-первых, обрати внимание откуда ты здесь берешь первую и последнюю станцию для маршрута.
во-вторых, сейчас есть возможность создать маршрут где первая и последняя станция будут одинаковые.
обрати внимание на то, что когда мы выбрали первую станцию и даем пользователю выбрать последнюю, то первую мы не отображаем.

2023-01-02 16:47 UTC, shilin-anton commented on part_3/main.rb
> +    end
еще, наверное, было бы не лишним добавить проверку, что бы нельзя было плодить одинаковые маршруты

2023-01-02 16:47 UTC, shilin-anton commented on part_3/main.rb
> +      #break if gets.chomp == "exit"
и поправь что бы exit останавливал работу приложения

2023-01-02 17:37 UTC, dmitry-tkachuk commented on part_3/main.rb
> +    if last >= (@stations.count) || last < 0 #last = gets.chomp.to_i - 1
пережитки прошлого

2023-01-02 17:45 UTC, dmitry-tkachuk commented on part_3/main.rb
> +    elsif @stations[number].trains == []
хорошо

2023-01-02 19:37 UTC, dmitry-tkachuk commented on part_3/main.rb
> +      route = Route.new(stations_list[first], stations_list[last])
done

2023-01-02 19:37 UTC, dmitry-tkachuk commented on part_3/main.rb
> +    end
done

2023-01-02 19:38 UTC, dmitry-tkachuk commented on part_3/main.rb
> +      return
done

2023-01-02 19:49 UTC, shilin-anton commented
good job

2023-01-02 19:49 UTC, merged